name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: ./.github/actions/initialize
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://npm.pkg.github.com
          scope: "@Himenon"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: |
          pnpm build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
